### ISSUE TITLE
Can't syncdb

### ISSUE THREAD

**Issue by RicoswLive** [MineID/MineID#2]
I become this error after executing this Command: 
python manage.py syncdb --migrate --noinput --settings=mineid.dev_settings

```
root@helium:/home/backend/MineID# python manage.py syncdb --migrate --noinput --settings=mineid.dev_settings
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/local/lib/python2.7/dist-packages/south/migration/__init__.py", line 173, in migrate_app
    Migrations.calculate_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 237, in calculate_dependencies
    migration.calculate_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 371, in calculate_dependencies
    for migration in self._get_dependency_objects("depends_on"):
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 351, in _get_dependency_objects
    for app, name in getattr(self.migration_class(), attrname, []):
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 323, in migration_class
    return self.migration().Migration
  File "/usr/local/lib/python2.7/dist-packages/south/utils/__init__.py", line 62, in method
    value = function(self)
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 312, in migration
    raise exceptions.UnknownMigration(self, sys.exc_info())
south.exceptions.UnknownMigration: Migration 'thumbnail:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 310, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/usr/local/lib/python2.7/dist-packages/sorl/thumbnail/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations
```

**Comment by caioariede** [comment]
@RicoswLive please try changing the following line in the requirements_core.txt file:

http://github.com/mariocesar/sorl-thumbnail/archive/master.zip#egg=sorl-thumbnail==11.12.1b

**to:**
sorl-thumbnail==12.2

**Comment by rbrenton** [comment]
http://github.com/mariocesar/sorl-thumbnail/archive/master.zip#egg=sorl-thumbnail==12.2

Collecting sorl-thumbnail==12.2 from http://github.com/mariocesar/sorl-thumbnail/archive/master.zip#egg=sorl-thumbnail==12.2 (from -r requirements_core.txt (line 20))
  Downloading http://github.com/mariocesar/sorl-thumbnail/archive/master.zip (571kB)
    100% |████████████████████████████████| 573kB 1.7MB/s
  Requested sorl-thumbnail==12.2 from http://github.com/mariocesar/sorl-thumbnail/archive/master.zip#egg=sorl-thumbnail==12.2 (from -r requirements_core.txt (line 20)), but installing version 12.4a1
Requirement already satisfied: gevent==1.0.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: greenlet==0.4.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: shortuuid>=0.3 in ./.venv/lib/python2.7/site-packages (from django-oauth2-provider==0.2.6.1->-r requirements_core.txt (line 13))
Requirement already satisfied: six in ./.venv/lib/python2.7/site-packages (from django-braces==1.4.0->-r requirements_core.txt (line 15))
Installing collected packages: sorl-thumbnail
  Found existing installation: sorl-thumbnail 12.4a1
    Uninstalling sorl-thumbnail-12.4a1:
      Successfully uninstalled sorl-thumbnail-12.4a1
  Running setup.py install for sorl-thumbnail ... done
Successfully installed sorl-thumbnail-12.4a1

 ./manage.py syncdb --migrate --noinput --settings=mineid.dev_settings
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/south/migration/__init__.py", line 173, in migrate_app
    Migrations.calculate_dependencies()
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 237, in calculate_dependencies
    migration.calculate_dependencies()
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 371, in calculate_dependencies
    for migration in self._get_dependency_objects("depends_on"):
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 351, in _get_dependency_objects
    for app, name in getattr(self.migration_class(), attrname, []):
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 323, in migration_class
    return self.migration().Migration
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/south/utils/__init__.py", line 62, in method
    value = function(self)
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 312, in migration
    raise exceptions.UnknownMigration(self, sys.exc_info())
south.exceptions.UnknownMigration: Migration 'thumbnail:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 310, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/var/www/mineid.example.org/htdocs/.venv/local/lib/python2.7/site-packages/sorl/thumbnail/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations

**Comment by rbrenton** [comment]
Fixed in pull request https://github.com/MineID/MineID/pull/9
